<a href="https://colab.research.google.com/github/Bhaswanth-A/Tensorflow-Deep-Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concepts of tensors using Tensorflow


## Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[5,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([[10.,6.],[1.,7.],[4.,9.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  6.],
       [ 1.,  7.],
       [ 4.,  9.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,5],
                       [3,5,6]],
                      [[4,5,1],
                       [2,9,0]],
                      [[3,6,1],
                       [7,6,1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 5],
        [3, 5, 6]],

       [[4, 5, 1],
        [2, 9, 0]],

       [[3, 6, 1],
        [7, 6, 1]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# tf.Variable
tensor1 = tf.Variable([1,3])
tensor2 = tf.constant([1,3])
tensor1, tensor2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [ ]:
tensor1[0].assign(9)
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 3], dtype=int32)>

In [ ]:
# Random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[2,5],
                            [4,8],
                            [1,9]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [4, 8],
       [1, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 9],
       [4, 8],
       [2, 5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [4, 8],
       [1, 9]], dtype=int32)>

In [ ]:
# Other ways to create tensors
tf.ones(shape=(10,5))

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(10,5))

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

In [ ]:
A.shape

TensorShape([2, 3, 4])

In [ ]:
ten1 = tf.random.Generator.from_seed(42)
ten1 = ten1.normal(shape=(3,4))
ten1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [ ]:
tf.size(ten1)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
ten1.shape

TensorShape([3, 4])

In [ ]:
# Get more info from tensors

rank_ten = tf.zeros(shape=(2,3,4,5), dtype=tf.float32)
rank_ten

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("Datatype of every element: ",rank_ten.dtype)
print("Number of dimensions (rank): ",rank_ten.ndim)
print("Shape of tensor: ",rank_ten.shape)
print("Elements along 0 axis: ",rank_ten.shape[0])
print("Elements along last axis: ",rank_ten.shape[-1])
print("Total number of elements in tensor: ",tf.size(rank_ten))
print("Total number of elements in tensor: ",tf.size(rank_ten).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along last axis:  5
Total number of elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor:  120


## Indexing tensors

Can be indexed like python lists

In [ ]:
rank_ten[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_ten[:2,:2,:,:2]

<tf.Tensor: shape=(2, 2, 4, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[3,4],
                             [1,2]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
rank_ten[:,-1,-1,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 2], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[1],
        [2]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 4],
        [1, 2]]], dtype=int32)>

Manipulating Tensors

In [ ]:
tensor = tf.constant([[10,7],
                     [3,4]])
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In [ ]:
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
y = tf.reshape(y, shape=(2,3))
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.tensordot(x,y, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Changing the datatype of a tensor

In [ ]:
B = tf.constant([5.2,4.5])
B.dtype

tf.float32

In [ ]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

## Aggregating Tensors

Condensing them from multiple values down to a smaller amount of values

In [ ]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 86, 55, 26, 94, 66, 36, 74,  1, 39, 28, 80,  3, 85, 94, 10,  6,
       95, 49, 42, 37, 65, 92, 97, 13, 19, 49, 41, 41, 86, 35, 83, 43, 78,
       64, 71,  4, 70, 77, 60, 68, 72, 61, 54, 15, 54, 63, 15, 24,  7])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2549>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=818>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.596846>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=817.7796>

### Find positional max and min

In [ ]:
tf.random.set_seed(42)
F = tf.random.normal(shape=[50,2])
F

<tf.Tensor: shape=(50, 2), dtype=float32, numpy=
array([[ 3.27468514e-01, -8.42625797e-01],
       [ 3.19433689e-01, -1.40755188e+00],
       [-2.38805985e+00, -1.03924787e+00],
       [-5.57323217e-01,  5.39707005e-01],
       [ 1.69943225e+00,  2.88936555e-01],
       [-1.50661159e+00, -2.64547437e-01],
       [-5.97224057e-01, -1.91711318e+00],
       [-6.20441437e-01,  8.50402296e-01],
       [-4.06047940e-01, -3.02584124e+00],
       [ 9.05846417e-01,  2.98559874e-01],
       [-2.25615546e-01, -7.61644304e-01],
       [-1.89171398e+00, -9.38471198e-01],
       [ 7.78522134e-01, -4.73388970e-01],
       [ 9.77726936e-01,  2.46944040e-01],
       [ 2.05737472e-01, -5.25623322e-01],
       [ 3.24100167e-01,  2.54540909e-02],
       [-1.06384970e-01, -6.36947513e-01],
       [ 1.16031218e+00,  2.50735909e-01],
       [-4.17284966e-01,  4.01257783e-01],
       [-1.41454422e+00, -5.93185663e-01],
       [-1.66172135e+00,  3.35671932e-01],
       [ 1.08156286e-01,  2.34796807e-01],
     

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=2.132039>

In [ ]:
tf.argmax(F).numpy()

array([40, 43])

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.normal(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ,
           -2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ,
            1.6994323 ,  0.28893656, -1.5066116 , -0.26454744,
           -0.59722406, -1.9171132 , -0.62044144,  0.8504023 ,
           -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
           -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,
            0.77852213, -0.47338897,  0.97772694,  0.24694404,
            0.20573747, -0.5256233 ,  0.32410017,  0.02545409,
           -0.10638497, -0.6369475 ,  1.1603122 ,  0.2507359 ,
           -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
           -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 ,
           -0.56668764, -0.35819843,  0.88698626,  0.5274477 ,
            0.70402247, -0.33421248]]]]], dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

In [ ]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>

In [ ]:
tf.argmax(G)

<tf.Tensor: shape=(1, 1, 1, 50), dtype=int64, numpy=
array([[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]]])>

In [ ]:
G_squeezed[tf.argmax(G_squeezed)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>

### One-hot encoding

In [ ]:
some_list = [0,1,2,3]

tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
H = tf.constant(np.arange(0,100,5))
H

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])>

In [ ]:
H = tf.reshape(H,shape=(4,5))
H

<tf.Tensor: shape=(4, 5), dtype=int64, numpy=
array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(4, 5), dtype=int64, numpy=
array([[   0,   25,  100,  225,  400],
       [ 625,  900, 1225, 1600, 2025],
       [2500, 3025, 3600, 4225, 4900],
       [5625, 6400, 7225, 8100, 9025]])>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.       , 2.236068 , 3.1622777, 3.8729832, 4.472136 ],
       [5.       , 5.477226 , 5.9160795, 6.3245554, 6.7082043],
       [7.0710673, 7.4161983, 7.7459664, 8.062257 , 8.366599 ],
       [8.660254 , 8.944272 , 9.219544 , 9.486833 , 9.746795 ]],
      dtype=float32)>